#!/usr/bin/with-contenv bash

source /assets/functions/00-container

PROCESS_NAME="openvpn"
check_container_initialized
check_service_initialized init
liftoff

print_info "Starting OpenVPN"
exec ovpn_run
