#!/usr/bin/with-contenv bash

source /assets/functions/00-container

### Sanity Test
sanity_var $HOSTNAME "Hostname"

if [ ! -f /etc/openvpn/ovpn_env.sh ]; then
    print_info "First run detected, creating configuration files"
    ovpn_genconfig -u udp://$HOSTNAME
    cd /etc/openvpn
    cp -R /assets/easy-rsa/vars /etc/openvpn
    ovpn_initpki nopass
fi

if var_true $ENABLE_LDAP ; then
    print_info "Enabling LDAP Authentication"
    mkdir -p /etc/openvpn/auth
    if [ ! -f /etc/openvpn/auth/auth-ldap.conf ]; then
      rm -rf /etc/openvpn/auth/auth-ldap.conf
    fi

    sanity_var LDAP_URI "LDAP URI"
    sanity_var LDAP_BIND_USER "LDAP Bind User/DN"
    sanity_var LDAP_BIND_PASS "LDAP Bind User Password"
    sanity_var LDAP_BASE_DN "LDAP Base DN"
    sanity_var LDAP_SEARCH_FILTER " LDAP Search Filter"
    
    LDAP_FOLLOW_REFERRALS=${LDAP_FOLLOW_REFERRALS:-yes}
    LDAP_TIMEOUT=${LDAP_TIMEOUT:-15}
    LDAP_REQUIRE_GROUP=${LDAP_REQUIRE_GROUP:-false}
    LDAP_GROUP_SEARCH_FILTER=${LDAP_GROUP_SEARCH_FILTER:-"(|(cn=developers)(cn=artists))"}
    LDAP_GROUP_BASE_DN=${LDAP_GROUP_BASE_DN:-$LDAP_BASE_DN}
    LDAP_GROUP_ATTRIBUTE=${LDAP_GROUP_ATTRIBUTE:-uniqueMember}

    cat <<EOF > /etc/openvpn/auth/auth-ldap.conf
<LDAP>
URL             $LDAP_URI
BindDN          $LDAP_BIND_USER
Password        $LDAP_BIND_PASS
Timeout         $LDAP_TIMEOUT
FollowReferrals $LDAP_FOLLOW_REFERRALS
</LDAP>

<Authorization>
BaseDN          "$LDAP_BASE_DN"
SearchFilter    "$LDAP_SEARCH_FILTER"
RequireGroup    $LDAP_REQUIRE_GROUP

    <Group>
      BaseDN    "$LDAP_GROUP_BASE_DN"
      SearchFilter  "$LDAP_GROUP_SEARCH_FILTER"
      MemberAttribute $LDAP_GROUP_ATTRIBUTE
    </Group>

</Authorization>
EOF

    sed -i '/openvpn-auth-ldap.so/c\plugin \/usr\/lib\/openvpn\/openvpn-auth-ldap.so \/etc\/openvpn\/auth\/auth-ldap.conf' /etc/openvpn/openvpn.conf
else
    sed -i '/openvpn-auth-ldap.so/c\#plugin \/usr\/lib\/openvpn\/openvpn-auth-ldap.so \/etc\/openvpn\/auth\/auth-ldap.conf' /etc/openvpn/openvpn.conf
fi

mkdir -p /var/log/openvpn

liftoff